AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: MyLambdaFunction::MyLambdaFunction.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: src/MyLambdaFunction/
      MemorySize: 256
      Timeout: 30
